# fly.toml app configuration file generated for jummah on 2023-06-08T13:01:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jummah"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
